updated all scripts to include helper functions

diff --git a/urlscript b/urlscript
--- a/urlscript
+++ b/urlscript
@@ -1,21 +1,29 @@
 #!/bin/bash
 
 # optional flag
-weburl="$1"
-
-shift
-
-while getopts ":f" flag; do
+while getopts ":f:" flag; do
   case ${flag} in
     f ) 
+      # take the url as an argument
+      weburl=$OPTARG
       # retrieve the content from a webpage and store it into a file 'urldisplay'
       wget -O urldisplay $weburl
       # filter and search for only links that start with http or https
       cat urldisplay | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" > webdisplay
       cat webdisplay
-      exit 0 ;;
+      exit 0
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument"
+      exit 1
+      ;;
+    h )
+      echo "[-f] [url] displays the links in the provided url, requires a url to be passed as an argument."
+      exit 1
+      ;;
     \? ) echo "No such option: $OPTARG use [-f] instead"
-      exit 1 ;;
+      exit 1
+      ;;
   esac
 done
 
